"""ResearchOS data models — the frozen contract for every stored object.

15 core objects, exactly as specified:

1. ResearchProject · 2. ResearchState · 3. Task · 4. Experiment · 5. Evidence · 6. Analysis ·
7. Claim · 8. Decision · 9. LiteraturePaper · 10. LiteratureRelation · 11. Skill ·
12. SkillVersion · 13. Audit · 14. Conflict · 15. PaperArtifact

plus the supporting objects they need (StateTransitionRequest, QueryPlan, NoveltyAudit,
PriorArtMatrix, BenchmarkRun, ReviewItem, TimelineEvent, AuthorNote, RedTeamReport, ...).
"""

from .analysis import Analysis, StatMethod, StatResult
from .audit import (
    Audit,
    AuditVerdict,
    Conflict,
    ConflictSource,
    Finding,
)
from .claim import Claim, ClaimHistoryEntry, Interpretation, RejectionBasis
from .common import (
    ArtifactRef,
    AuditKind,
    ChangeClass,
    ClaimStatus,
    ConflictKind,
    ConflictResolution,
    EvidenceLevel,
    EvidenceType,
    ExperimentStatus,
    FulltextStatus,
    GapKind,
    ID_PREFIXES,
    MechanismRung,
    NoveltyVerdict,
    Provenance,
    ReadinessDimension,
    RelationType,
    RiskLevel,
    RosModel,
    Severity,
    SourceKind,
    SourceRef,
    SOURCE_TRUST,
    StrEnum,
    TaskPriority,
    TaskPurpose,
    TaskStatus,
    TransitionStatus,
    Tri,
    VerificationStatus,
    canonical_json,
    content_hash,
    id_kind,
    new_id,
    sha256_bytes,
    sha256_file,
    sha256_json,
    sha256_text,
    utcnow,
)
from .decision import (
    CHANGE_CLASS_OF,
    GUARDED_PATHS,
    Decision,
    DecisionKind,
    StateOperation,
    StateOp,
    StateTransitionRequest,
    guarded_root,
    guarded_state_hash,
)
from .evidence import Evidence, EvidenceLink
from .experiment import (
    Arm,
    Experiment,
    ExperimentDesign,
    MetricDirection,
    MetricRef,
    ResultSummary,
    TrainingBudget,
    Variable,
    VariableKind,
    assess_experiment_level_from_design,
)
from .literature import (
    COVERAGE_THRESHOLDS,
    FORBIDDEN_NOVELTY_PHRASES,
    REQUIRED_FAMILIES,
    GapRecord,
    LiteratureClaim,
    LiteratureClaimKind,
    LiteratureCoverage,
    LiteraturePaper,
    LiteratureRelation,
    MatrixCell,
    MatrixColumn,
    MatrixRow,
    NodeKind,
    NoveltyAudit,
    NoveltyMatch,
    PlannedQuery,
    PriorArtMatrix,
    ProviderKind,
    ProviderRecord,
    QueryFamily,
    QueryPlan,
)
from .paper import (
    CitationRef,
    GroundedSentence,
    GroundingReport,
    GroundingViolation,
    GroundingViolationCode,
    NumberRef,
    PaperArtifact,
    PaperReadiness,
    PaperSection,
    ReadinessDimensionResult,
    RedTeamQuestion,
    RedTeamReport,
    SectionDraft,
    StyleCategory,
    StyleFinding,
)
from .project import ResearchProject
from .research_state import (
    CoreQuestion,
    Frontier,
    LiteratureState,
    OpenQuestion,
    PriorWorkRef,
    PriorityItem,
    QuestionKind,
    ResearchState,
    SkillState,
)
from .review import ReviewItem, ReviewKind
from .skill import (
    BenchmarkRun,
    BenchmarkSuite,
    BenchmarkTask,
    SandboxFinding,
    SandboxReport,
    SkillCapability,
    SkillCard,
    SkillDependency,
    SkillGap,
    SkillQualityMetrics,
    SkillSource,
    SkillStatus,
    SkillTrust,
    SkillVersion,
    TaskOutcome,
)
from .task import FindingKind, Task, TaskFinding
from .timeline import AuthorNote, NoteKind, TimelineEvent, TimelineEventKind

__all__ = [
    # 15 core
    "ResearchProject",
    "ResearchState",
    "Task",
    "Experiment",
    "Evidence",
    "Analysis",
    "Claim",
    "Decision",
    "LiteraturePaper",
    "LiteratureRelation",
    "SkillCard",
    "SkillVersion",
    "Audit",
    "Conflict",
    "PaperArtifact",
    # supporting
    "Analysis",
    "Arm",
    "ArtifactRef",
    "AuditKind",
    "AuditVerdict",
    "AuthorNote",
    "BenchmarkRun",
    "BenchmarkSuite",
    "BenchmarkTask",
    "CHANGE_CLASS_OF",
    "COVERAGE_THRESHOLDS",
    "CitationRef",
    "ClaimHistoryEntry",
    "ClaimStatus",
    "ChangeClass",
    "ConflictKind",
    "ConflictResolution",
    "ConflictSource",
    "CoreQuestion",
    "DecisionKind",
    "EvidenceLevel",
    "EvidenceLink",
    "EvidenceType",
    "ExperimentDesign",
    "ExperimentStatus",
    "FORBIDDEN_NOVELTY_PHRASES",
    "Finding",
    "FindingKind",
    "Frontier",
    "FulltextStatus",
    "GUARDED_PATHS",
    "GapKind",
    "GapRecord",
    "GroundedSentence",
    "GroundingReport",
    "GroundingViolation",
    "GroundingViolationCode",
    "ID_PREFIXES",
    "Interpretation",
    "LiteratureClaim",
    "LiteratureClaimKind",
    "LiteratureCoverage",
    "LiteraturePaper",
    "LiteratureRelation",
    "LiteratureState",
    "MatrixCell",
    "MatrixColumn",
    "MatrixRow",
    "MechanismRung",
    "MetricDirection",
    "MetricRef",
    "NodeKind",
    "NoteKind",
    "NoveltyAudit",
    "NoveltyMatch",
    "NoveltyVerdict",
    "NumberRef",
    "OpenQuestion",
    "PaperReadiness",
    "PaperSection",
    "PlannedQuery",
    "PriorArtMatrix",
    "PriorWorkRef",
    "PriorityItem",
    "Provenance",
    "ProviderKind",
    "ProviderRecord",
    "QueryFamily",
    "QueryPlan",
    "QuestionKind",
    "ReadinessDimension",
    "ReadinessDimensionResult",
    "RedTeamQuestion",
    "RedTeamReport",
    "RejectionBasis",
    "RelationType",
    "RequiredFamilies",
    "ResultSummary",
    "ReviewItem",
    "ReviewKind",
    "RiskLevel",
    "RosModel",
    "SandboxFinding",
    "SandboxReport",
    "SectionDraft",
    "Severity",
    "SkillCapability",
    "SkillDependency",
    "SkillGap",
    "SkillQualityMetrics",
    "SkillSource",
    "SkillState",
    "SkillStatus",
    "SkillTrust",
    "SOURCE_TRUST",
    "SourceKind",
    "SourceRef",
    "StatMethod",
    "StatResult",
    "StateOperation",
    "StateOp",
    "StateTransitionRequest",
    "StrEnum",
    "StyleCategory",
    "StyleFinding",
    "Task",
    "TaskFinding",
    "TaskOutcome",
    "TaskPriority",
    "TaskPurpose",
    "TaskStatus",
    "TimelineEvent",
    "TimelineEventKind",
    "TrainingBudget",
    "TransitionStatus",
    "Tri",
    "Variable",
    "VariableKind",
    "VerificationStatus",
    "assess_experiment_level_from_design",
    "canonical_json",
    "content_hash",
    "guarded_root",
    "guarded_state_hash",
    "id_kind",
    "new_id",
    "sha256_bytes",
    "sha256_file",
    "sha256_json",
    "sha256_text",
    "utcnow",
    "REQUIRED_FAMILIES",
]

#: Alias so ``from researchos.models import REQUIRED_FAMILIES`` and the documented name both work.
RequiredFamilies = REQUIRED_FAMILIES
