"""The ResearchOS Kernel — global research state, permissions, transitions, provenance."""

from .conflicts import TRUST_ORDER, ConflictLedger
from .errors import (
    ClaimTransitionError,
    ConflictError,
    EvidenceError,
    GroundingError,
    ImmutableResourceError,
    ImportError_,
    LiteratureError,
    PermissionDenied,
    ProjectExists,
    ProjectNotFound,
    ProvenanceError,
    ResearchOSError,
    SilentStateChangeError,
    SkillError,
    StateRevisionConflict,
    TaskBoundaryViolation,
    TransitionError,
    VerificationError,
)
from .events import ChainVerification, EventLog, EventRecord, GENESIS_HASH
from .kernel import ResearchKernel
from .levels import (
    LADDER,
    aggregate_level,
    completed_level_of_experiment,
    cross_setting_supported,
    independent_experiments,
    level_of_analysis,
    level_of_evidence,
    level_of_experiment,
    max_level,
    replication_count,
)
from .paths import DISPOSABLE_DIRS, ENTITY_DIRS, MARKER, STANDARD_DIRS, ProjectPaths
from .permissions import (
    AGENT_CAPABILITIES,
    ALL_CAPABILITIES,
    EXTERNAL_SKILL_CAPABILITIES,
    GUARD_REASONS,
    HUMAN_ONLY_CAPABILITIES,
    Cap,
    PolicyEngine,
    Principal,
    PrincipalKind,
    ResourceClass,
    assert_mutable,
)
from .provenance import (
    capture_provenance,
    config_hash,
    environment_info,
    git_info,
    register_artifact,
    verify_artifact,
    verify_artifacts,
)
from .state import StateManager
from .store import EntityStore, ProjectStore, YamlIO, merge_missing
from .tasks import TaskManager
from .timeline import TimelineRecorder
from .transitions import TransitionManager

__all__ = [
    "AGENT_CAPABILITIES",
    "ALL_CAPABILITIES",
    "EXTERNAL_SKILL_CAPABILITIES",
    "GUARD_REASONS",
    "HUMAN_ONLY_CAPABILITIES",
    "LADDER",
    "TRUST_ORDER",
    "Cap",
    "ChainVerification",
    "ClaimTransitionError",
    "ConflictError",
    "ConflictLedger",
    "DISPOSABLE_DIRS",
    "ENTITY_DIRS",
    "EntityStore",
    "EventLog",
    "EventRecord",
    "EvidenceError",
    "GENESIS_HASH",
    "GroundingError",
    "ImmutableResourceError",
    "ImportError_",
    "LiteratureError",
    "MARKER",
    "PermissionDenied",
    "PolicyEngine",
    "Principal",
    "PrincipalKind",
    "ProjectExists",
    "ProjectNotFound",
    "ProjectPaths",
    "ProjectStore",
    "ProvenanceError",
    "ResearchKernel",
    "ResearchOSError",
    "ResourceClass",
    "STANDARD_DIRS",
    "SilentStateChangeError",
    "SkillError",
    "StateManager",
    "StateRevisionConflict",
    "TaskBoundaryViolation",
    "TaskManager",
    "TimelineRecorder",
    "TransitionError",
    "TransitionManager",
    "VerificationError",
    "YamlIO",
    "aggregate_level",
    "assert_mutable",
    "capture_provenance",
    "completed_level_of_experiment",
    "config_hash",
    "cross_setting_supported",
    "environment_info",
    "git_info",
    "independent_experiments",
    "level_of_analysis",
    "level_of_evidence",
    "level_of_experiment",
    "max_level",
    "merge_missing",
    "register_artifact",
    "replication_count",
    "verify_artifact",
    "verify_artifacts",
]
